<a href="https://colab.research.google.com/github/djoseprogramming/PSMDSRC-103/blob/main/Seatwork_6_1_Programming_Exercise_Getting_Started_with_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Seatwork 6.1 Programming Exercise: Getting Started with Pandas!

Submitted by Daryll Jose

Using the 2019_Yellow_Taxi_Trip_Data.csv dataset, accomplish the following items and submit a PDF of the notebook:

1. (25 marks) Create a DataFrame by reading in the 2019_Yellow_Taxi_Trip_Data.csv file. Examine the first 5 rows.
2. (25 marks) Find the dimensions (number of rows and number of columns) in the data.
3. (25 marks) Using the data in the 2019_Yellow_Taxi_Trip_Data.csv file, calculate summary statistics for the fare_amount, tip_amount, tolls_amount, and total_amount columns.
4. (25 marks) Isolate the fare_amount, tip_amount, tolls_amount, and total_amount for the longest trip by distance (trip_distance).
Submit the whole notebook as PDF, with the exercise section at the end of the notebook. Include a link to your Github repo in the comment section.

### 1.

In [40]:
import pandas as pd

# Import the file
filepath = '/content/2019_Yellow_Taxi_Trip_Data.csv'
taxi_df = pd.read_csv(filepath)

# Examine the first 5 rows
taxi_df.head()

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2,2019-10-23T16:39:42.000,2019-10-23T17:14:10.000,1,7.93,1,N,138,170,1,29.5,1.0,0.5,7.98,6.12,0.3,47.90,2.5
1,1,2019-10-23T16:32:08.000,2019-10-23T16:45:26.000,1,2.00,1,N,11,26,1,10.5,1.0,0.5,0.00,0.00,0.3,12.30,0.0
2,2,2019-10-23T16:08:44.000,2019-10-23T16:21:11.000,1,1.36,1,N,163,162,1,9.5,1.0,0.5,2.00,0.00,0.3,15.80,2.5
3,2,2019-10-23T16:22:44.000,2019-10-23T16:43:26.000,1,1.00,1,N,170,163,1,13.0,1.0,0.5,4.32,0.00,0.3,21.62,2.5
4,2,2019-10-23T16:45:11.000,2019-10-23T16:58:49.000,1,1.96,1,N,163,236,1,10.5,1.0,0.5,0.50,0.00,0.3,15.30,2.5

#### 2.

In [15]:
# Find the dimensions
print(f'''Row: {taxi_df.shape[0]}
Col: {taxi_df.shape[1]}''')

Row: 10000
Col: 18

#### 3.

In [32]:
# Create a class for repeating summary stats
class summary():

    def __init__(self, df):
        self.mean = df.mean()
        self.median = df.median()
        self.mode = df.mode()
        self.quantile = df.quantile([0.01, 0.05, 0.5, 0.95, 0.99])
        self.min = df.min()
        self.max = df.max()

    def printDetails(self, title):
        print(f'{title.upper()} SUMMARY')
        print(f'Mean: {self.mean}')
        print(f'Median: {self.median}')
        print(f'Mode: {self.mode}')
        print(f'Quantile: {self.quantile}')
        print(f'Min: {self.min}')
        print(f'Max: {self.max}')
        print()

summary(taxi_df['fare_amount']).printDetails("Fare Amount")
summary(taxi_df['tip_amount']).printDetails("Tip Amount")
summary(taxi_df['tolls_amount']).printDetails("Tolls Amount")
summary(taxi_df['total_amount']).printDetails("Total Amount")

FARE AMOUNT SUMMARY
Mean: 15.106313
Median: 10.0
Mode: 0    52.0
Name: fare_amount, dtype: float64
Quantile: 0.01     3.000
0.05     4.500
0.50    10.000
0.95    52.000
0.99    62.005
Name: fare_amount, dtype: float64
Min: -52.0
Max: 176.0

TIP AMOUNT SUMMARY
Mean: 2.6344939999999997
Median: 2.0
Mode: 0    0.0
Name: tip_amount, dtype: float64
Quantile: 0.01     0.000
0.05     0.000
0.50     2.000
0.95    10.361
0.99    15.860
Name: tip_amount, dtype: float64
Min: 0.0
Max: 43.0

TOLLS AMOUNT SUMMARY
Mean: 0.623447
Median: 0.0
Mode: 0    0.0
Name: tolls_amount, dtype: float64
Quantile: 0.01    0.00
0.05    0.00
0.50    0.00
0.95    6.12
0.99    6.12
Name: tolls_amount, dtype: float64
Min: -6.12
Max: 612.0

TOTAL AMOUNT SUMMARY
Mean: 22.564659
Median: 16.3
Mode: 0    11.8
Name: total_amount, dtype: float64
Quantile: 0.01     6.3000
0.05     9.3000
0.50    16.3000
0.95    67.1075
0.99    82.4000
Name: total_amount, dtype: float64
Min: -65.92
Max: 671.8

#### 4.

In [39]:
# Get the longest distance and provide stats
longdist = taxi_df[taxi_df['trip_distance'] == taxi_df['trip_distance'].max()]
longdist[['fare_amount', 'tip_amount', 'tolls_amount', 'total_amount']]

      fare_amount  tip_amount  tolls_amount  total_amount
8338        176.0       18.29          6.12        201.21